---
kind: Service
apiVersion: v1
metadata:
  name: devops-app-lb-service
  namespace: kubernetes-cluster-rakeshsharma04
spec:
  type: LoadBalancer
  selector:
    app: devops-app-service
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-app-config
  namespace: kubernetes-cluster-rakeshsharma04
data:
  ENV: 'PROD'
  APP_TYPE: 'Webapp'

---
apiVersion: v1
kind: Secret
metadata:
  name: devops-app-secret
  namespace: kubernetes-cluster-rakeshsharma04
type: Opaque
data:
  password: d2ViYXBwMTIzNA==
  private_key: NTYyZ2dzdjU2Nw==

# passord ====> webapp1234
# private_key ====> 562ggsv567

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
  namespace: kubernetes-cluster-rakeshsharma04
spec:
  selector:
      matchLabels:
        app: devops-app-service
  replicas: 4
  template:
    metadata:
      labels:
        app: devops-app-service
    spec:
      containers:
       - name: devops-app-service
         image: rs79696046/i-rakeshsharma04-master:latest
         ports:
         - containerPort: 8080
         envFrom:
          - configMapRef:
              name: devops-app-config
          - secretRef:
              name: devops-app-secret
